# Add your funding platforms here. Supported options:
# github: username
# patreon: username
# open_collective: username
# ko_fi: username
# buy_me_a_coffee: username
# custom: ["https://your-link.com"]

github: ranajahanzaib
